bmarketo/Controllers/ContactsController.cs
using bmarketo.Contexts;
using bmarketo.Models.Entities;
using bmarketo.Services;
using bmarketo.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace bmarketo.Controllers
{
    public class ContactsController : Controller
    {
        private readonly ContactFormService _contactFormService;
        public ContactsController(ContactFormService contactFormService)
        {
            _contactFormService = contactFormService;
        }


        public IActionResult Index()
        {
            ViewData["Title"] = "Contact Us";
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> RegisterContactForm(ContactFormViewModel contactFormViewModel)
        {
            if (ModelState.IsValid)
            {
                    if (await _contactFormService.RegisterContactFormAsync(contactFormViewModel))
                    {
                        return RedirectToAction("index", "home");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Something went wrong when creating the form. Try Again.");
                    }
            }

            ViewData["Title"] = "Register";
            return View(contactFormViewModel);






        }


    }
}

bmarketo/Controllers/LoginController.cs
using bmarketo.Contexts;
using bmarketo.Models.Entities;
using bmarketo.Services;
using bmarketo.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace bmarketo.Controllers
{
   
    public class LoginController : Controller
    {

        private readonly AuthenticationService _auth;

        public LoginController(AuthenticationService auth)
        {
            _auth = auth;
     
        }

        public IActionResult Index(string ReturnUrl = null!)
        {
            var viewModel = new UserLoginViewModel();
            if(ReturnUrl != null)
                viewModel.ReturnUrl = ReturnUrl;
    
            return View(viewModel);
        }

        //FIXA DETTA IMORN 

        [HttpPost]


        public async Task<IActionResult> Index(UserLoginViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
             

                if (await _auth.LoginAsync(viewModel))

                    return LocalRedirect(viewModel.ReturnUrl);

                ModelState.AddModelError("", "Incorrect email or password.");
            }

            return View(viewModel);
        }




    }
}

bmarketo/Controllers/LogoutController.cs
using bmarketo.Contexts.Identity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace bmarketo.Controllers
{
    public class LogoutController : Controller
    {
        private readonly SignInManager<AppUser> _signInManager;

        public LogoutController(SignInManager<AppUser> signInManager)
        {
            _signInManager = signInManager;
        }

        public async Task<IActionResult> Index()
        {
            if (_signInManager.IsSignedIn(User))
                await _signInManager.SignOutAsync();
            return LocalRedirect("/");
        }
    }
}

bmarketo/Controllers/ProductsController.cs
using bmarketo.Contexts;
using bmarketo.Models;
using bmarketo.Services;
using bmarketo.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace bmarketo.Controllers;




public class ProductsController : Controller
{
  
    private readonly ProductService _productService;
    private readonly TagService _tagService; 
    public ProductsController(ProductService productService, TagService tagService)
    {
        _productService = productService;
        _tagService = tagService;
    }




    public async Task <IActionResult> Index()
    {
        ViewData["Title"] = "Index";
        var viewmodel = new ProductRegistrationViewModel
        {
            Products = await _productService.GetAllAsync()
        };
        return View(viewmodel);
    }


    [Authorize(Roles ="admin")]
    public async Task<IActionResult> RegisterProduct()
    {
        ViewBag.Tags = await _tagService.GetTagsAsync();
        var viewmodel = new ProductRegistrationViewModel
        {
            Products = await _productService.GetAllAsync()
        };
        return View(viewmodel);
    }


 //FIXA HÄR UNDER IMORN

    [Authorize(Roles = "admin")]
    [HttpPost]
    public async Task<IActionResult> RegisterProduct(ProductRegistrationViewModel productRegistrationViewModel, string[] tags )
    {
        if (ModelState.IsValid)
        {

            //if (await _productService.CreateAsync(productRegistrationViewModel))
            //    await _productService.AddProductTagsAsync(productRegistrationViewModel, tags);


            // Fungerande kod:
            var product = await _productService.CreateAsyncTwo(productRegistrationViewModel);
            if(product != null)
            {
                await _productService.AddProductTagsAsync(productRegistrationViewModel, tags); // ta bort denna om ej går. 
                if (productRegistrationViewModel.ProductImage != null)
                    await _productService.UploadImageAsync(product, productRegistrationViewModel.ProductImage);
                return RedirectToAction("Index", "Admin");
            }
            ViewBag.Tags = await _tagService.GetTagsAsync(tags);
            ModelState.AddModelError("", "Something went wrong when making the product.");
        }


        return View();
    }




    public IActionResult Search()
    {
        ViewData["Title"] = "Search for products";
        return View();
    }

}

bmarketo/Views/Partials/_EndBoxesCollection.cshtml
@model GridCollectionViewModel


@if (Model.GridItems != null)
{
    
        @foreach (var item in Model.GridItems)
        {
            <partial name="/Views/Partials/_EndBoxesPartial.cshtml" model="item" />
          
     
        }
}

bmarketo/Views/Partials/_FooterPartial.cshtml
<footer class="contactfooter">

    <div class="container">
        <p>@DateTime.Now.Year BMERKETO. All rights reserved.</p>
    </div>
</footer>

bmarketo/Views/Partials/_GridCollection.cshtml
@model GridCollectionViewModel

@if (Model != null){
    <section class="cardgrid">
        @if(!string.IsNullOrEmpty(Model.Title))
        {
           <h1 class="headline">@Model.Title</h1>
        }
       

        @if (Model.BreadCrumbs != null)
        {
            <nav class="breadcrumbs">
                <ol class="breadcrumb">
                    @foreach (var breadcrumb in Model.BreadCrumbs)
                    {
                        <li class="breadcrumb-item"><a href="#">@breadcrumb</a></li>
                    }

                </ol>
            </nav>
        }

        @if (Model.GridItems != null)
        {
            <div class="container">
                @foreach (var item in Model.GridItems)
                {
                    <partial name="/Views/Partials/_GridCollectionItem.cshtml" model="item"/>
                }
            </div>
        }


        @if (Model.LoadMore)
        {
            <button class="btn-load-more">LOAD MORE <i class="fa-solid fa-arrow-rotate-right" style="font-size:12px;"></i></button>
        }


    </section>
    <!--Cardgrid end-->
}

bmarketo/Views/Partials/_GridCollectionItem.cshtml
<!--fixa detta imorn innan inlämning-->

@model GridCollectionItemViewModel

<a asp-controller="ProductDetails" asp-action="Index" asp-route-id="@Model.Id" class="card">
    <img src="@Url.Content("~/Images/products/" + Model.ProductImage) class="topimg" alt="@Model.Name">
    <div class="card-body">
        <div class="title">
        <p class="head-text">@Model.Name</p>
        </div>
        <div class="info">
        <p>@Model.Description</p>
        <p class="paragraph">$@Model.Price</p>
            <i class="fa-solid fa-cart-shopping"></i>
        </div>
        
    </div>
</a>

bmarketo/Views/Partials/_HeaderPartial.cshtml
<header>
    <div class="container">
        <img class="logo" src="/Images/logo.svg" alt="" />
        <div class="menudiv">
            <nav class="hide" id="menu">
                <a class="link" asp-controller="Home" asp-action="index">HOME</a>
                <a class="link" asp-controller="Products" asp-action="index">PRODUCTS</a>
                <a class="link" asp-controller="Contacts" asp-action="index">CONTACT</a>
            </nav>
            <nav class="menu-icons">
                <a class="link" asp-controller="Products" asp-action="Search">
                    <i class="fa-sharp fa-solid fa-magnifying-glass"></i>
                </a>


                @if (signInManager.IsSignedIn(User))
                {
                    <a class="link" asp-controller="account" asp-action="index">@User.Identity?.Name</a>
                    <a class="link" asp-controller="Logout" asp-action="index">Logout</a>
                }
                else
                {
                    <a class="link" asp-controller="Login" asp-action="index">Login</a>
                }
                
                <a class="link" asp-controller="Cart" asp-action="index">
                    <i class="fa-solid fa-cart-shopping"></i>
                </a>
            </nav>
        </div>

        <div class="toggle">
            <button class="btn-white" data-option="toggle" data-target="#menu"><i class="fa-solid fa-bars"></i></button>
        </div>
    </div>
</header>

bmarketo/Views/Partials/_InfoBoxPartial.cshtml
<div class="infobox">
    <p class="headline">UP TO </p>
    <p class="paragraph">50 % OFF</p>
    <p class="part-two">Get The Best Price</p>
    <p class="part-three">Get 50 percent off when buying 3 items!</p>
    <a link href="#">Discover More!</a>
</div>

bmarketo/Views/Partials/_NewProductsPartial.cshtml
@model HomeIndexViewModel
<h1 style="font-weight:bold; font-family: roboto;">
@foreach(var title in Model.BestCollection.Title)
{
     @title;
   
}
</h1>

<div class="breadcrumbs">
    @foreach (var breadcrumb in Model.BestCollection.BreadCrumbs)
    {
        <span>@breadcrumb</span>
        @if (!breadcrumb.Equals(Model.BestCollection.BreadCrumbs.Last()))
        {
            <span class="separator">/</span>
        }
    }
</div>

<div class="container" style="justify-content:center;">
@foreach (var product in Model.BestCollection.GridItems)
{
    <a asp-controller="ProductDetails" asp-action="Index" asp-route-id="@product.Id" class="card" style="width: 272px; color: black;">
        <img src="~/Images/products/@product.ProductImage" class="topimg" alt="@product.Name" style="width: 270px; height: 295px;">
        <div class="card-body">
            <div class="title">
                <p class="head-text" style="font-weight:bold; font-size:22px;">@product.Name</p>
            </div>
            <div class="info">
                <p>@product.Description</p>
                <p class="paragraph">$@product.Price</p>
                <i class="fa-solid fa-cart-shopping"></i>
            </div>
        </div>
    </a>

}
</div>

bmarketo/Views/Partials/_PercentageOffBox.cshtml
@model HomeIndexViewModel


        @foreach (var product in Model.PercentageOff.GridItems)
        {
            <a asp-controller="ProductDetails" asp-action="Index" asp-route-id="@product.Id" class="card" style="width: 272px; color: black;">
                <img src="~/Images/products/@product.ProductImage" class="topimg" alt="@product.Name" style="width: 270px; height: 295px;">
                <div class="card-body">
                    <div class="title">
                        <p class="head-text" style="font-weight:bold; font-size:22px;">@product.Name</p>
                    </div>
                    <div class="info">
                        <p>@product.Description</p>
                        <p class="paragraph">$@product.Price</p>
                        <p class="paragraph" style="text-decoration:line-through">$@product.OldPrice</p>
                        <i class="fa-solid fa-cart-shopping"></i>
                    </div>
                </div>
            </a>
        }

    

bmarketo/Views/Partials/_PercentageOffBox2.cshtml
@model HomeIndexViewModel


<div class="container" style="justify-content:center;">

    
    @foreach (var product in Model.PercentageOff.GridItems)
    {
        <a asp-controller="ProductDetails" asp-action="Index" asp-route-id="@product.Id" class="card" style="width: 272px; color: black;">
            <img src="~/Images/products/@product.ProductImage" class="topimg" alt="@product.Name" style="width: 270px; height: 295px;">
            <div class="card-body">
                <div class="title">
                    <p class="head-text" style="font-weight:bold; font-size:22px;">@product.Name</p>
                </div>
                <div class="info">
                    <p>@product.Description</p>
                    <p class="paragraph">$@product.Price</p>
                    <i class="fa-solid fa-cart-shopping"></i>
                </div>
            </div>
        </a>
    }


</div>

bmarketo/Views/Partials/_PercentageOffCollection.cshtml
@model GridCollectionViewModel

@if (Model.GridItems != null)
{
    
        @foreach (var item in Model.GridItems)
        {
            <partial name="/Views/Partials/_PercentageOffBox.cshtml" model="item" />
          
     
        }
}

bmarketo/Views/Partials/_PercentageOffCollection2.cshtml
@model GridCollectionViewModel

@if (Model.GridItems != null)
{
    
        @foreach (var item in Model.GridItems)
        {
            <partial name="/Views/Partials/_PercentageOffBox2.cshtml" model="item" />
        }
   
}

bmarketo/Views/Partials/_PopularPartial.cshtml
@model HomeIndexViewModel
<h1 style="font-weight:bold; font-family: roboto;">
@foreach(var title in Model.BestCollection.Title)
{
     @title;
   
},
</h1>

<div class="breadcrumbs">
    @foreach (var breadcrumb in Model.BestCollection.BreadCrumbs)
    {
        <span>@breadcrumb</span>
        @if (!breadcrumb.Equals(Model.BestCollection.BreadCrumbs.Last()))
        {
            <span class="separator">/</span>
        }
    }
</div>
<div class="container" style="justify-content:center;">
@foreach (var product in Model.BestCollection.GridItems)
{
    <a asp-controller="ProductDetails" asp-action="Index" asp-route-id="@product.Id" class="card" style="width: 272px; color: black;">
        <img src="~/Images/products/@product.ProductImage" class="topimg" alt="@product.Name" style="width: 270px; height: 295px;">
        <div class="card-body">
            <div class="title">
                <p class="head-text" style="font-weight:bold; font-size:22px;">@product.Name</p>
            </div>
            <div class="info">
                <p>@product.Description</p>
                <p class="paragraph">$@product.Price</p>
                <i class="fa-solid fa-cart-shopping"></i>
            </div>
        </div>
    </a>

}
</div>

bmarketo/Views/Partials/_TopSellingCollection.cshtml
@model GridCollectionViewModel

@if (Model.GridItems != null)
{
    
        @foreach (var item in Model.GridItems)
        {
            <partial name="/Views/Partials/_TopSellingProductsPartial.cshtml" model="item" />
          
     
        }
}

bmarketo/Views/Partials/_TopSellingProductsPartial.cshtml
@model HomeIndexViewModel


@foreach (var product in Model.TopSelling.GridItems)
{
    <a asp-controller="ProductDetails" asp-action="Index" asp-route-id="@product.Id" class="card" style="width: 272px; color: black;">
        <img src="~/Images/products/@product.ProductImage" class="topimg" alt="@product.Name" style="width: 270px; height: 295px;">
        <div class="card-body">
            <div class="title">
                <p class="head-text" style="font-weight:bold; font-size:22px;">@product.Name</p>
            </div>
            <div class="info">
                <p>@product.Description</p>
                <p class="paragraph">$@product.Price</p>
                <i class="fa-solid fa-cart-shopping"></i>
            </div>
        </div>
    </a>
}