bmarketo/Controllers/ProductDetailsController.cs
using bmarketo.Contexts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using bmarketo.Models.Entities;
namespace bmarketo.Controllers
{
    public class ProductDetailsController : Controller
    {
        public IActionResult Index()
        {
       
            ViewData["Title"] = "ProductDetail";
            return View();
        }
    }
}

bmarketo/Controllers/ProductsController.cs
using bmarketo.Contexts;
using bmarketo.Models;
using bmarketo.Services;
using bmarketo.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace bmarketo.Controllers;




public class ProductsController : Controller
{
  
    private readonly ProductService _productService;
    private readonly TagService _tagService; 
    public ProductsController(ProductService productService, TagService tagService)
    {
        _productService = productService;
        _tagService = tagService;
    }




    public async Task <IActionResult> Index()
    {
        ViewData["Title"] = "Index";
        var viewmodel = new ProductRegistrationViewModel
        {
            Products = await _productService.GetAllAsync()
        };
        return View(viewmodel);
    }


    [Authorize(Roles ="admin")]
    public async Task<IActionResult> RegisterProduct()
    {
        ViewBag.Tags = await _tagService.GetTagsAsync();
        var viewmodel = new ProductRegistrationViewModel
        {
            Products = await _productService.GetAllAsync()
        };
        return View(viewmodel);
    }


 //FIXA HÄR UNDER IMORN

    [Authorize(Roles = "admin")]
    [HttpPost]
    public async Task<IActionResult> RegisterProduct(ProductRegistrationViewModel productRegistrationViewModel, string[] tags )
    {
        if (ModelState.IsValid)
        {

            //if (await _productService.CreateAsync(productRegistrationViewModel))
            //    await _productService.AddProductTagsAsync(productRegistrationViewModel, tags);


            // Fungerande kod:
            var product = await _productService.CreateAsyncTwo(productRegistrationViewModel);
            if(product != null)
            {
                await _productService.AddProductTagsAsync(productRegistrationViewModel, tags); // ta bort denna om ej går. 
                if (productRegistrationViewModel.ProductImage != null)
                    await _productService.UploadImageAsync(product, productRegistrationViewModel.ProductImage);
                return RedirectToAction("Index", "Admin");
            }
            ViewBag.Tags = await _tagService.GetTagsAsync(tags);
            ModelState.AddModelError("", "Something went wrong when making the product.");
        }


        return View();
    }




    public IActionResult Search()
    {
        ViewData["Title"] = "Search for products";
        return View();
    }

}

bmarketo/Views/Products/Index.cshtml
@model ProductRegistrationViewModel


<section class="productview">
<div class="container" style="justify-content:center;">

    @foreach(var product in Model.Products)
    {
        <a asp-controller="ProductDetails" asp-action="Index" asp-route-id="@product.ArticleNumber" class="card" style="width:272px; color:black;">
        <img src="~/Images/products/@product.ProductImage" class="topimg" alt="@product.Name" style="width:270px; height:295px;">
            <div class="card-body">
                <div class="title">
                    <p class="head-text" style="font-weight:bold; font-size:22px;">@product.Name</p>
                </div>
                <div class="info">
                    <p>@product.Description</p>
                    <p class="paragraph">$@product.Price</p>
                    <i class="fa-solid fa-cart-shopping"></i>
                </div>

            </div>
        </a>
    }

</div>
</section>

bmarketo/Views/Products/RegisterProduct.cshtml
@model ProductRegistrationViewModel
@{
    ViewData["Title"] = "Register Product";
    
    
}

<div class="d-flex justify-content-center" style="margin-bottom:540px">
    <div class="col-6">
        <h1>Add Your Product:</h1>
        <form enctype="multipart/form-data" method="post" novalidate>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3">
                <label asp-for="Name" class="form-label"></label>
                <input asp-for="Name" class="form-control"/>
                <small><span asp-validation-for="Name" class="text-danger"></span></small>
            </div>

            <div class="mb-3">
                <label asp-for="ArticleNumber" class="form-label"></label>
                <input asp-for="ArticleNumber" class="form-control" />
                <small><span asp-validation-for="ArticleNumber" class="text-danger"></span></small>
            </div>

            <div class="mb-3">
                <label asp-for="Price" class="form-label"></label>
                <input asp-for="Price" class="form-control" />
                <small><span asp-validation-for="Price" class="text-danger"></span></small>
            </div>

            <div class="mb-3">
                <label asp-for="OldPrice" class="form-label"></label>
                <input asp-for="OldPrice" class="form-control" />
                <small><span asp-validation-for="OldPrice" class="text-danger"></span></small>
            </div>

            <div class="mb-3">
                <label asp-for="Description" class="form-label"></label>
                <textarea asp-for="Description" class="form-control no-resize" rows="4" ></textarea>
                <small><span asp-validation-for="Description" class="text-danger"></span></small>
            </div>


            @foreach(SelectListItem tag in ViewBag.Tags)
            {
                <div>
                    <input type="checkbox" name="Tags" value="@tag.Value" checked="@tag.Selected" class="form-check-input"/>
                    <label for="@tag.Value" class="form-check-label">@tag.Text</label>
                </div>
            }

            <div class="mb-3">
                <label asp-for="ProductImage" class="form-label"></label>
                <input type="file" asp-for="ProductImage" class="form-control" rows="4" />
                <small><span asp-validation-for="ProductImage" class="text-danger"></span></small>
            </div>
            <div class="cardgrid mt-2">
                <button type="submit">Add</button>
            </div>
        </form>
        <h1>Added Products</h1>

        <table class="table">
            <thead>
                <tr>
                    <th >Name</th>
                    <th >Price</th>
                    <th >Description</th>
                    <th >Image</th>
                </tr>
            </thead>
            <tbody>
              
                    @foreach(var product in Model.Products)
                    {
                        <tr>
                            <td>@product.Name</td>
                        <td>@product.Price</td>
                        <td>@product.Description</td>
                        <td><img src="~/Images/products/@product.ProductImage" alt="@product.Name" style="width: 100px; height:100px;"/></td>
                        </tr>
                    }
                  
                
            </tbody>
        </table>


    </div>
</div>