bmarketo/Controllers/LoginController.cs
using bmarketo.Contexts;
using bmarketo.Models.Entities;
using bmarketo.Services;
using bmarketo.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace bmarketo.Controllers
{
   
    public class LoginController : Controller
    {

        private readonly AuthenticationService _auth;

        public LoginController(AuthenticationService auth)
        {
            _auth = auth;
     
        }

        public IActionResult Index(string ReturnUrl = null!)
        {
            var viewModel = new UserLoginViewModel();
            if(ReturnUrl != null)
                viewModel.ReturnUrl = ReturnUrl;
    
            return View(viewModel);
        }

        //FIXA DETTA IMORN 

        [HttpPost]


        public async Task<IActionResult> Index(UserLoginViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
             

                if (await _auth.LoginAsync(viewModel))

                    return LocalRedirect(viewModel.ReturnUrl);

                ModelState.AddModelError("", "Incorrect email or password.");
            }

            return View(viewModel);
        }




    }
}

bmarketo/Controllers/UserRegisterController.cs
using bmarketo.Services;
using bmarketo.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace bmarketo.Controllers
{
    public class UserRegisterController : Controller
    {
        private readonly AuthenticationService _auth;
        public UserRegisterController(AuthenticationService auth)
        {
            _auth = auth;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task <IActionResult> Index(UserRegisterViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                if (await _auth.UserAlreadyExistsAsync(x=> x.Email == viewModel.Email))
                    ModelState.AddModelError("", "A user with that email already exist.");
                

                if(await _auth.RegisterUserAsync(viewModel))
                    return RedirectToAction("index","login");
            }

            return View(viewModel);
        }
    }
}

bmarketo/Views/Login/Index.cshtml
@model UserLoginViewModel
@{
    ViewData["Title"] = "Login";
}

<section class="loginform">
    <div class="container">
        <img src="./images/logo.svg" />
        <form method="post" enctype="multipart/form-data" novalidate asp-route-ReturnUrl="@Model.ReturnUrl">
            <div asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <h6>Please Login to your account</h6>
            <hr>
            <label asp-for="Email">Email*<a link asp-controller="UserRegister" asp-action="index" style="font-weight:bold; margin-left:20px;">Dont have account yet? Get One here!</a></label>
            <div class="col-sm-10">
                <input asp-for="Email" class="form-control" placeholder="Enter your email here">
                <small><span asp-validation-for="Email" class="text-danger"></span></small>
            </div>
            <label asp-for="Password">Password*<a link href="#" style="margin-left:20px;">Forgot your password?</a></label>
            <div class="col-sm-10">
                <input asp-for="Password" class="form-control" placeholder="Enter your password here">
                <small><span asp-validation-for="Password" class="text-danger"></span></small>
            </div>
        </div>
        <div class="terms from-checkbox-group">
            <label asp-for="RememberMe" class="custom-checkbox">
                Keep me logged in:
                <input asp-for="RememberMe"/>
                <span class="checkmark"></span>
            </label>
        </div>
            <button type="submit" class="btn-theme">login</button>
        </form>
    </div>
</section>